#/usr/bin/env zsh

source "$ZSHDOTDIR/zshrc.aliases"
source "$ZSHDOTDIR/zshrc.functions"


### color ###
autoload -Uz colors
colors

setopt prompt_subst
PROMPT='%F{cyan}%n%f@%F{green}%m%f %~ $ '

#OSによって別ファイルから読み込み
case "${OSTYPE:-}" in
	linux*)  source "$ZSHDOTDIR/zshrc.linux"
			if [ $UID = 0 ]; then
				PROMPT='%F{red}%n%f@%F{green}%m%f %~ $ '
			fi
			;;
	darwin*) source "$ZSHDOTDIR/zshrc.darwin" ;;
esac


### General ###
setopt correct						#スペルチェック

### cd ###
setopt auto_cd						#cd省略
setopt auto_pushd					#ディレクトリをスタックに追加
setopt pushd_ignore_dups			#pushdした時スタックに重複させない

### Completion ###
autoload -U compinit; compinit		#自動補完
setopt magic_equal_subst			#引数にも補完を有効にする
setopt magic_equal_subst			#=以降も補完
setopt auto_list					#補完候補を一覧で表示
setopt auto_menu					#Tab連打で補完を順に表示
setopt complete_in_word				#語の途中でもカーソル位置で補完
setopt print_eight_bit				#日本語8ビットを通す
zstyle ':completion:*default' menu select=1						#補完候補をハイライト
zstyle ':completion:*default' menu_highlight select=2			#補完候補を十字キーでも選択


### history ###
HISTFILE=~/.zsh_history				#履歴ファイルの指定
HISTSIZE=100000						#メモリに保存される履歴サイズ
SAVEHIST=100000						#履歴ファイルに保存される数
setopt append_history				#zsh同時使用時、historyを上書きせず追加する
setopt extended_history				#zshの開始・終了時刻を記録
setopt hist_ignore_dups				#直前と同じコマンドは保存しない
setopt hist_ignore_space			#先頭がスペースの場合は履歴を保存しない
setopt share_history				#プロセスごとにhistoryを共有
setopt hist_ignore_all_dups			#重複した履歴は古いものを削除
setopt hist_no_store				#historyコマンドは履歴に残さない



### zstyle ###
